### ISSUE TITLE
Refatorar funções

### ISSUE THREAD

**Issue by mldzs** [hudsonbrendon/pysympla#5]
Será se não vale a pena dividir a função "orders" em outras funções? "Orders" está responsável por 3 endpoints. Tem uma feature ainda não criada que é a de "Participantes", ela contém 5 endpoints, sendo 3 deles do tipo GET e 2 do tipo POST. Ficará inviável usar uma função só, e isso quebrará o padrão atual de centralizar alguns endpoints em uma função.
Ex: 
participants_by_order()
orders_by_event()
order_by_identifier()

em vez de só

orders()

**Comment by hudsonbrendon** [comment]
Sim, pode ficar a vontade para desenvolver dessa forma.
